### ISSUE TITLE
Updater?

### ISSUE THREAD

**Issue by 100pcrack** [RedInquisitive/Screenshot-Tool#2]
Just an idea:
Java program checks if there's a new version available. If there's one, it shows an alert to the user to go to master.zip link or even to download the update.

**Comment by RedInquisitive** [comment]
I don't think that this is a big enough project to deserve an updater :laughing:. I mean, I _could_ program it... but I don't think it is worth my time to add such a feature. This program is more of just a personal project that I decided to share, so I only really programmed it for myself. If I programmed an updater, it wouldn't affect me because I would already have the update!

If I program something worthwhile I'll look into it then, but for now I'll close this. Don't worry, your other idea was golden, though!
